[2024-02-25T14:49:23.233-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drivers_to_bq.run_etl manual__2024-02-25T20:49:18.748125+00:00 [queued]>
[2024-02-25T14:49:23.236-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drivers_to_bq.run_etl manual__2024-02-25T20:49:18.748125+00:00 [queued]>
[2024-02-25T14:49:23.236-0600] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-25T14:49:23.243-0600] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_etl> on 2024-02-25 20:49:18.748125+00:00
[2024-02-25T14:49:23.248-0600] {standard_task_runner.py:60} INFO - Started process 27622 to run task
[2024-02-25T14:49:23.251-0600] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'drivers_to_bq', 'run_etl', 'manual__2024-02-25T20:49:18.748125+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/driversDag.py', '--cfg-path', '/var/folders/2c/plc265_s31s2djb7299kj1fh0000gn/T/tmpqg36u_ts']
[2024-02-25T14:49:23.253-0600] {standard_task_runner.py:88} INFO - Job 16: Subtask run_etl
[2024-02-25T14:49:23.277-0600] {task_command.py:423} INFO - Running <TaskInstance: drivers_to_bq.run_etl manual__2024-02-25T20:49:18.748125+00:00 [running]> on host vamsees-macbook-pro.local
[2024-02-25T14:49:23.307-0600] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='drivers_to_bq' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-02-25T20:49:18.748125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-25T20:49:18.748125+00:00'
[2024-02-25T14:49:23.309-0600] {driversDag.py:26} INFO - getting drivers data
[2024-02-25T14:49:23.309-0600] {logging_mixin.py:188} INFO - this is the extract >>>
[2024-02-25T14:49:23.309-0600] {logging_mixin.py:188} INFO - year >>> 2023
[2024-02-25T14:49:23.310-0600] {logging_mixin.py:188} INFO - printing data >>>  {'year': 2023}
[2024-02-25T14:49:23.310-0600] {logging_mixin.py:188} INFO - getting response >>>
[2024-02-25T14:50:08.531-0600] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-02-25T14:50:08.536-0600] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 27622. PIDs of all processes in the group: [27622]
[2024-02-25T14:50:08.536-0600] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 27622
[2024-02-25T14:51:08.570-0600] {process_utils.py:149} WARNING - process psutil.Process(pid=27622, name='Python', status='running', started='14:49:23') did not respond to SIGTERM. Trying SIGKILL
[2024-02-25T14:51:08.573-0600] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 27622
[2024-02-25T14:51:08.582-0600] {process_utils.py:79} INFO - Process psutil.Process(pid=27622, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='14:49:23') (27622) terminated with exit code Negsignal.SIGKILL
[2024-02-25T14:51:08.582-0600] {standard_task_runner.py:175} ERROR - Job 16 was killed before it finished (likely due to running out of memory)
