[2024-02-24T16:26:02.866-0600] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: drivers_to_bq.run_etl manual__2024-02-24T22:23:44.264159+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
