[2024-02-24T16:21:06.409-0600] {processor.py:161} INFO - Started process (PID=89796) to work on /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:21:06.411-0600] {processor.py:830} INFO - Processing file /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py for tasks to queue
[2024-02-24T16:21:06.412-0600] {logging_mixin.py:188} INFO - [2024-02-24T16:21:06.412-0600] {dagbag.py:538} INFO - Filling up the DagBag from /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:21:06.421-0600] {logging_mixin.py:188} INFO - [2024-02-24T16:21:06.413-0600] {dagbag.py:348} ERROR - Failed to import: /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
Traceback (most recent call last):
  File "/Users/vamseekrishna/Desktop/F1_Data_Warehouse/f1datawarehouse/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
ModuleNotFoundError: No module named 'airflow.providers.google'
[2024-02-24T16:21:06.422-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:21:06.484-0600] {processor.py:183} INFO - Processing /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py took 0.075 seconds
[2024-02-24T16:22:04.914-0600] {processor.py:161} INFO - Started process (PID=89881) to work on /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:22:04.915-0600] {processor.py:830} INFO - Processing file /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py for tasks to queue
[2024-02-24T16:22:04.916-0600] {logging_mixin.py:188} INFO - [2024-02-24T16:22:04.915-0600] {dagbag.py:538} INFO - Filling up the DagBag from /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:22:04.923-0600] {logging_mixin.py:188} INFO - [2024-02-24T16:22:04.916-0600] {dagbag.py:348} ERROR - Failed to import: /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
Traceback (most recent call last):
  File "/Users/vamseekrishna/Desktop/F1_Data_Warehouse/f1datawarehouse/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
ModuleNotFoundError: No module named 'airflow.providers.google'
[2024-02-24T16:22:04.924-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:22:04.987-0600] {processor.py:183} INFO - Processing /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py took 0.074 seconds
[2024-02-24T16:23:04.125-0600] {processor.py:161} INFO - Started process (PID=89976) to work on /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:23:04.127-0600] {processor.py:830} INFO - Processing file /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py for tasks to queue
[2024-02-24T16:23:04.127-0600] {logging_mixin.py:188} INFO - [2024-02-24T16:23:04.127-0600] {dagbag.py:538} INFO - Filling up the DagBag from /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:23:04.135-0600] {logging_mixin.py:188} INFO - [2024-02-24T16:23:04.128-0600] {dagbag.py:348} ERROR - Failed to import: /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
Traceback (most recent call last):
  File "/Users/vamseekrishna/Desktop/F1_Data_Warehouse/f1datawarehouse/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
ModuleNotFoundError: No module named 'airflow.providers.google'
[2024-02-24T16:23:04.136-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:23:04.202-0600] {processor.py:183} INFO - Processing /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py took 0.078 seconds
[2024-02-24T16:24:10.070-0600] {processor.py:161} INFO - Started process (PID=90076) to work on /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:24:10.071-0600] {processor.py:830} INFO - Processing file /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py for tasks to queue
[2024-02-24T16:24:10.071-0600] {logging_mixin.py:188} INFO - [2024-02-24T16:24:10.071-0600] {dagbag.py:538} INFO - Filling up the DagBag from /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:24:10.079-0600] {logging_mixin.py:188} INFO - [2024-02-24T16:24:10.072-0600] {dagbag.py:348} ERROR - Failed to import: /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
Traceback (most recent call last):
  File "/Users/vamseekrishna/Desktop/F1_Data_Warehouse/f1datawarehouse/lib/python3.9/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py", line 2, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator
ModuleNotFoundError: No module named 'airflow.providers.google'
[2024-02-24T16:24:10.081-0600] {processor.py:842} WARNING - No viable dags retrieved from /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py
[2024-02-24T16:24:10.169-0600] {processor.py:183} INFO - Processing /Users/vamseekrishna/Desktop/F1_Data_Warehouse/dags/tobq.py took 0.100 seconds
