[2024-02-25T11:38:16.484-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drivers_to_bq.run_etl manual__2024-02-25T17:38:11.672399+00:00 [queued]>
[2024-02-25T11:38:16.487-0600] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drivers_to_bq.run_etl manual__2024-02-25T17:38:11.672399+00:00 [queued]>
[2024-02-25T11:38:16.488-0600] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-25T11:38:16.496-0600] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_etl> on 2024-02-25 17:38:11.672399+00:00
[2024-02-25T11:38:16.502-0600] {standard_task_runner.py:60} INFO - Started process 18157 to run task
[2024-02-25T11:38:16.507-0600] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'drivers_to_bq', 'run_etl', 'manual__2024-02-25T17:38:11.672399+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/driversDag.py', '--cfg-path', '/var/folders/2c/plc265_s31s2djb7299kj1fh0000gn/T/tmp1qsk_rkz']
[2024-02-25T11:38:16.509-0600] {standard_task_runner.py:88} INFO - Job 14: Subtask run_etl
[2024-02-25T11:38:16.541-0600] {task_command.py:423} INFO - Running <TaskInstance: drivers_to_bq.run_etl manual__2024-02-25T17:38:11.672399+00:00 [running]> on host vamsees-macbook-pro.local
[2024-02-25T11:38:16.574-0600] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='drivers_to_bq' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-02-25T17:38:11.672399+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-25T17:38:11.672399+00:00'
[2024-02-25T11:38:16.575-0600] {driversDag.py:26} INFO - getting drivers data
[2024-02-25T11:38:16.575-0600] {logging_mixin.py:188} INFO - this is the extract >>>
[2024-02-25T11:38:16.576-0600] {logging_mixin.py:188} INFO - year >>> 2023
[2024-02-25T11:38:16.576-0600] {logging_mixin.py:188} INFO - getting response >>>
[2024-02-25T12:17:46.736-0600] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-02-25T12:17:46.748-0600] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 18157. PIDs of all processes in the group: [18157]
[2024-02-25T12:17:46.748-0600] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 18157
[2024-02-25T12:18:46.766-0600] {process_utils.py:149} WARNING - process psutil.Process(pid=18157, name='Python', status='running', started='11:38:16') did not respond to SIGTERM. Trying SIGKILL
[2024-02-25T12:18:46.775-0600] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 18157
[2024-02-25T12:18:46.779-0600] {process_utils.py:79} INFO - Process psutil.Process(pid=18157, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='11:38:16') (18157) terminated with exit code Negsignal.SIGKILL
[2024-02-25T12:18:46.779-0600] {standard_task_runner.py:175} ERROR - Job 14 was killed before it finished (likely due to running out of memory)
